language: go

script: go test -v ./...

before_deploy:
  - GOOS=linux GOARCH=amd64 go build -o basic-$TRAVIS_TAG-linux-amd64 github.com/billglover/go-owl/examples/basic 
  - GOOS=linux GOARCH=arm go build -o basic-$TRAVIS_TAG-linux-arm github.com/billglover/go-owl/examples/basic
  - GOOS=darwin GOARCH=amd64 go build -o basic-$TRAVIS_TAG-darwin-amd64 github.com/billglover/go-owl/examples/basic
  - GOOS=windows GOARCH=amd64 go build -o basic-$TRAVIS_TAG.exe github.com/billglover/go-owl/examples/basic
  - GOOS=linux GOARCH=amd64 go build -o multicast-$TRAVIS_TAG-linux-amd64 github.com/billglover/go-owl/examples/multicast
  - GOOS=linux GOARCH=arm go build -o multicast-$TRAVIS_TAG-linux-arm github.com/billglover/go-owl/examples/multicast
  - GOOS=darwin GOARCH=amd64 go build -o multicast-$TRAVIS_TAG-darwin-amd64 github.com/billglover/go-owl/examples/multicast
  - GOOS=windows GOARCH=amd64 go build -o multicast-$TRAVIS_TAG.exe github.com/billglover/go-owl/examples/multicast

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - basic-$TRAVIS_TAG-linux-amd64
    - basic-$TRAVIS_TAG-linux-arm
    - basic-$TRAVIS_TAG-darwin-amd64
    - basic-$TRAVIS_TAG.exe
    - multicast-$TRAVIS_TAG-linux-amd64
    - multicast-$TRAVIS_TAG-linux-arm
    - multicast-$TRAVIS_TAG-darwin-amd64
    - multicast-$TRAVIS_TAG.exe

  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - go clean